### ISSUE TITLE
Query-String löschen für jede Regel einzeln

### ISSUE THREAD

**Issue by tristanlins** [psi-4ward/redirect4ward#5]
Aktuell lässt sich der Query-String nur allgemein löschen, eine Einstellung pro Weiterleitungs-Regel währe auch sinnvoll, weil man es nicht immer global braucht, den Query-String zu löschen.

**Comment by psi-4ward** [comment]
Das ist etwas tricky da ich zuerst den Query-String lösche und dann die Datenbank nach Matches durchsuche.
Du darfst dir aber gern was überlegen und pull-requesten ;)
